name              'remote_install'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Provides an opinionated way to download and install remote software'
version           '2.1.3'
source_url        'https://github.com/sous-chefs/remote_install'
issues_url        'https://github.com/sous-chefs/remote_install/issues'
chef_version      '>= 12.7'

supports 'centos'
supports 'debian'
supports 'fedora'
supports 'oracle'
supports 'redhat'
supports 'freebsd'
supports 'scientific'
supports 'mac_os_x'
supports 'ubuntu'
supports 'windows'
