name              'remote_install'
maintainer        'Chef Software, Inc.'
maintainer_email  'cookbooks@chef.io'
license           'Apache-2.0'
description       'Provides an opinionated way to download and install remote software'
version           '2.0.0'

supports 'centos'
supports 'debian'
supports 'fedora'
supports 'oracle'
supports 'redhat'
supports 'freebsd'
supports 'scientific'
supports 'mac_os_x'
supports 'ubuntu'
supports 'windows'

source_url 'https://github.com/chef-cookbooks/remote_install'
issues_url 'https://github.com/chef-cookbooks/remote_install/issues'
chef_version '>= 12.7'
